# Site settings
# These are used to personalize your new site.
title: Teaundra Thompson # your name here
logo: "/images/senior_Port_270x270.png" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cybersecurity (class of 2026)
  <br /><br />
  <a href="/pdf/Resume_Fall25.pdf">View My Resume</a>
repository: "csci-csu/csci-portfolio"
github_username:  ladyTootie # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

